package com.wsheng.suanfa;

import java.util.HashSet;
import java.util.Set;

/**
     * 389 Find the Difference

     Given two strings s and t which consist of only lowercase letters.

     String t is generated by random shuffling string s and then add one more letter at a random position.

     Find the letter that was added in t.

     Example:

     Input:
     s = “abcd”
     t = “abcde”

     Output:
     e

     Explanation:
     ‘e’ is the letter that was added.
 * @Auther: wsheng
 * @Date: 2018/11/7 10:05
 * @Description:
 */
public class Solution389 {

    public static char findTheDifference(String s,String t){

       char[] s1 =  s.toCharArray();
       char[] t1 =  t.toCharArray();
       Set<Character> set = new HashSet<>();
       for(char c : s1) set.add(c);
       for (char c1: t1){
           if (set.add(c1)) return c1;
        }
        return 0;
    }

    public static char findTheDifference1(String s,String t){
        int ret = 0;
        for (int i = 0; i < s.length(); i++) {
            ret -= (int)s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            ret += (int)t.charAt(i);
        }
        return (char)ret;
    }

    public static char findTheDifference2(String s,String t){
        char diff = 0;
        for (char c: s.toCharArray()) {
            diff = (char) (diff^c);
        }
        for (char c: t.toCharArray()) {
            diff = (char) (diff^c);
        }
        return diff;
    }



    public static void main(String[] args) {
      char n =   Solution389.findTheDifference2("abcd","akbcd");
      System.out.println(n);
    }
}
